formkit/formkit

packages/i18n/src/locales/fr.ts

Fixed one spelling mistake and rephrase two strange-sounding validation errors.

Fix French i18n mistakes

---

packages/i18n/src/locales/nl.ts

Add missing newer ui strings and change one translation to be equal to another.

Update Dutch translation

---

packages/i18n/src/locales/ar.ts
packages/i18n/src/locales/da.ts
packages/i18n/src/locales/de.ts
packages/i18n/src/locales/en.ts
packages/i18n/src/locales/es.ts
packages/i18n/src/locales/fa.ts
packages/i18n/src/locales/fi.ts
packages/i18n/src/locales/fr.ts
packages/i18n/src/locales/he.ts
packages/i18n/src/locales/hr.ts
packages/i18n/src/locales/id.ts
packages/i18n/src/locales/it.ts
packages/i18n/src/locales/ko.ts
packages/i18n/src/locales/nl.ts
packages/i18n/src/locales/pl.ts
packages/i18n/src/locales/pt.ts
packages/i18n/src/locales/ru.ts
packages/i18n/src/locales/tr.ts
packages/i18n/src/locales/vi.ts
packages/i18n/src/locales/zh.ts
packages/rules/__tests__/alpha_spaces.spec.ts
packages/rules/src/alpha_spaces.ts
packages/rules/src/index.ts
packages/tailwindcss/README.md

Adds alpha_spaces validation rule with testing and locale message translations.
Issue: https://github.com/formkit/formkit/issues/83

Adds alpha_spaces rule validation

---

README.md
packages/i18n/src/locales/pl.ts

I've reviewed my translations on real examples and some of them were not as natural as they could. 
I've made sentences easier to read and understand by anyone and covered most cases possible for each field to look the most accurate to any situation.

Polish language structure fixes

---

packages/tailwindcss/src/index.ts

fix(tailwindcss): :bug: fixes #143

---

packages/tailwindcss/package.json
packages/themes/package.json
packages/themes/src/index.ts
packages/themes/src/unocss/index.ts
yarn.lock

Adding UnoCSS to themes and fixing dependencies for themes.

Adding UnoCSS to themes

---

packages/themes/package.json
packages/themes/src/index.ts
packages/themes/src/windicss/index.ts
yarn.lock

adds the plugin for windicss formkit variants with custom attributes and message states by using the theme function

feat(themes): :sparkles: added windicss formkit variants plugin

---

packages/rules/__tests__/required.spec.ts
packages/rules/src/required.ts

Issue: [#171](https://github.com/formkit/formkit/issues/171) 
[PR for docs update](https://github.com/formkit/docs-content/pull/34)

Adds trim argument logic to required field along with supporting tests

---

README.md
packages/core/src/schema.ts
packages/vue/README.md
packages/vue/__tests__/FormKitSchema.spec.ts

Should fix #232 but I have not been able to confirm yet

Fix $formkit shorthand not propagating key

---

packages/i18n/src/locales/fy.ts

Update fy.ts (i18n)

---

packages/i18n/src/locales/uz.ts

I’ve completed the Uzbek language translation.
- Adds Uzbek (uz) language translation.

i18n: Uzbek (uz) translation

---

packages/i18n/src/index.ts
packages/i18n/src/locales/uk.ts

- added 🇺🇦 Ukrainian (`uk`) translation.
@luan-nk-nguyen, please update https://formkit.com/essentials/internationalization page.

i18n: 🇺🇦 Ukrainian (uk) translation

---

packages/i18n/src/locales/es.ts

I saw that two translations were in English. I have not opened an issue as it is a small fix.

Fix spanish translation.

---

packages/themes/package.json

This fixes #376. by specifying the types using `typesVersions`.

fix(config): :bug: fixes cannot find module of submodules

---

packages/i18n/src/locales/hu.ts

Fix typo in hungarian translation.

[Typo] - Update hu.ts

---

packages/validation/__tests__/validation.spec.ts
packages/validation/src/validation.ts

This is the fix for this issue: https://github.com/formkit/formkit/issues/452

fix(validation): required rule doesn't work as expected

---

packages/i18n/src/locales/pt.ts

Updates the translation for pt using #423 thanks to @dbomfim !

updates pt translation #423

---

packages/i18n/src/formatters.ts

Fixes #488 error messages being one day ahead or behind because of timezones

fixes timezone dates being one day ahead or behind

---

packages/inputs/src/features/normalizeBoxes.ts

Fixes #517 by using slugify utils instead of kebab

uses slugify instead of kebab for boxes options

---

api-extractor.json
packages/core/src/config.ts
packages/core/src/index.ts
packages/core/src/node.ts
packages/core/src/schema.ts
packages/core/src/store.ts
packages/observer/src/index.ts
packages/validation/src/index.ts
packages/validation/src/validation.ts
packages/vue/src/FormKitSchema.ts
packages/vue/src/composables/useInput.ts
packages/vue/src/defaultConfig.ts
packages/vue/src/index.ts

Fixes all api-extractor warnings by exposing all public api correctly

Fixes all api-extractor warnings by exposing all public api correctly

---

examples/src/vue/examples/MultiStep.vue
packages/addons/__tests__/__snapshots__/multistep.spec.ts.snap
packages/addons/__tests__/multistep.spec.ts
packages/addons/src/plugins/multiStep/multiStepPlugin.ts
packages/addons/src/plugins/multiStep/sections/tab.ts

Multi-step input tab order respects DOM order

---

packages/themes/src/tailwindcss/genesis/index.ts

changes `day` to `dayCell` to use new datepicker structure.

fixes tailwindcss genesis

---

pnpm-lock.yaml
scripts/build.mjs
scripts/utils.mjs

Fixed problems with building on windows system because of pathing issues.

Fix windows build

---

packages/inputs/src/features/files.ts

Fixes a file not being able to be added after resetting the node.

fixes #762

---

packages/i18n/src/index.ts
packages/i18n/src/locales/is.ts
packages/i18n/src/locales/mn.ts

adds icelandic and mongolian translations

---

packages/vue/src/bindings.ts

adds node null check before blur event

---

packages/themes/src/index.ts

move iconName check to handle all non-string cases

---

packages/addons/src/plugins/autoHeightTextarea.ts

Fixes https://github.com/formkit/formkit/issues/839#issue-1812555309

Fix textarea auto-height if form is reset

---

packages/i18n/src/index.ts
packages/i18n/src/locales/lt.ts

Had to throw pluralisation function there `getByQuantity`.
By the given quantity it returns singular or plural with the correct suffix in Lithuanian.

i18n: Adds Lithuanian translations

---

packages/i18n/src/index.ts

Added two missing language codes to export
may close #885

Adds tet and lv codes to export

---

packages/themes/src/tailwindcss/genesis/index.ts

Update tailwindcss genesis theme

Update tailwindcss genesis theme

---

packages/rules/__tests__/alphanumeric.spec.ts
packages/rules/__tests__/contains_alphanumeric.spec.ts
packages/rules/src/alpha.ts
packages/rules/src/alpha_spaces.ts
packages/rules/src/alphanumeric.ts
packages/rules/src/confirm.ts
packages/rules/src/contains_alpha.ts
packages/rules/src/contains_alpha_spaces.ts
packages/rules/src/contains_alphanumeric.ts
packages/rules/src/contains_lowercase.ts
packages/rules/src/contains_numeric.ts
packages/rules/src/contains_symbol.ts
packages/rules/src/contains_uppercase.ts
packages/rules/src/date_before.ts
packages/rules/src/date_between.ts
packages/rules/src/date_format.ts
packages/rules/src/ends_with.ts
packages/rules/src/lowercase.ts
packages/rules/src/max.ts
packages/rules/src/min.ts
packages/rules/src/not.ts
packages/rules/src/number.ts
packages/rules/src/require_one.ts
packages/rules/src/required.ts
packages/rules/src/starts_with.ts
packages/rules/src/symbol.ts
packages/rules/src/uppercase.ts
packages/rules/src/url.ts

fix: correct and simplify RegEx in validation rules

---

packages/core/src/node.ts
packages/vue/src/composables/createInput.ts

Added the V type to allow for node types to stop the tsc error on create input

Added types for createInput and FormKitTypeDefinition

---

packages/core/src/node.ts
packages/inputs/src/props.ts
packages/vue/src/bindings.ts
packages/vue/src/composables/createInput.ts

Last pr didn't not cover test, amended areas in code to fix this.

Added types where definition is used

---

packages/cli/src/createApp.ts

related: https://github.com/formkit/formkit/issues/1233

fix(cli): add more dependencies for nuxt app

---

packages/i18n/src/locales/de.ts

fixed german translation #1293

---

packages/cli/__tests__/__snapshots__/cli.spec.ts.snap
packages/cli/src/exportInput.ts
packages/cli/src/theme.ts
packages/core/src/events.ts
packages/core/src/node.ts
packages/core/src/store.ts
packages/nuxt/playground/formkit.theme.ts
packages/observer/src/index.ts
packages/vue/src/FormKit.ts
packages/vue/src/FormKitKitchenSink.ts

I noticed with prettier that there was a strange white space char in these strings and I replaced it with a normal space char

fix: replaced strange char with space

---

packages/core/src/reset.ts

I am mostly sure this shouldn't be here, unless I am missing some important context 😅

chore: remove console.log
