packages/core/src/index.ts
Some type exports in the core packages which are marked as public are missing.
=> Adds missing type exports which are marked as public.

packages/inputs/src/composables/outer.ts, packages/vue/src/bindings.ts
I propose this change to make the error styles via [data-invalid] class in css visibles when the form is submitted
=> Add data-invalid on form submission

packages/core/src/node.ts, packages/nuxt/src/runtime/plugin.mjs, packages/vue/src/FormKit.ts, packages/vue/src/FormKitSchema.ts, packages/vue/src/plugin.ts
@justin-schroeder base on you feedback, moved FormKitSchema to the plugin installation. 
- register `FormKitSchema` as a component in `createPlugin`
- align exports of `FormKit` & `FormKitSchema`
- add `alias` and `schemaAlias` props to the `FormKitOptions` type
Hope that's better
=> fix: add formkitschema in plugin creation

README.md, packages/inputs/src/compose.ts
The custom component schema suffix incorrectly uses the extensions prefix instead of the suffix. This change corrects this behavior.
=> fix(inputs): invalid useSchema suffix

packages/core/__tests__/node.spec.ts, packages/core/src/reset.ts
At the moment no event will be emitted when the node reset functionality is used.
With these changes, a `reset` event will be emitted at the end of a node reset call.
=> Adds node reset event

packages/themes/src/tailwindcss/index.ts
By adding the theme function from tailwind, it makes it possible to add custom data attributes and message states.
```js
module.exports = {
...
plugins: [
require('@formkit/tailwindcss')
],
theme: {
formkit: {
attributes: ['custom'],
messageStates: ['success']
}
}
}
```
=> feat(themes): :sparkles: adds theme to the tailwindcss plugin

package.json, yarn.lock
fixes this error I saw on my dev machine:
```
error postcss-nesting@9.0.0: The engine "node" is incompatible with this module. Expected version "12 - 16". Got "17.8.0"
error Found incompatible module.
=> Bump postcss-nesting for node 17 compat

packages/themes/src/css/genesis/inputs/checkbox-and-radio.css, packages/themes/src/css/genesis/inputs/file.css, packages/vue/src/FormKit.ts, packages/vue/src/FormKitIcon.ts
This helps with Vue stark trace, if something went wrong. Some other tools also use names, like Histoire. 
Note: `FormKitSchema` already has `name` defined.
=> fix: define name for vue components

packages/themes/src/css/genesis/inputs/checkbox-and-radio.css
The style of checkbox in genesis theme has broken by  https://github.com/formkit/formkit/commit/678f6729de99bc859381f5efe1e6f0cea4448adc of PR #314.
fixed it to work as originally intended.
=> fix: fix checkbox css selector

packages/tailwindcss/playground/src/theme.js, packages/themes/src/index.ts
Adds support for input families:
```js
generateClasses({
'family:text': 'classes to apply to text inputs here'
})
```
=> Adds family support to generateClasses

packages/themes/src/tailwindcss/index.ts, packages/themes/src/unocss/index.ts, packages/themes/src/windicss/index.ts
It fixes Tailwindcss/Windicss/Unocss to not get repeaters invalid state for inner inputs states.
It adds a new feature of grouping that came with Tailwindcss 3.2, that makes it possible to target groups when specifing variants to nested rule sets, by setting a `group/*` to the outer class of the element you want to group and to adding `formkit-invalid/*:text-red-500` to the section you want to style based on the group state.
=> fix(themes): :bug: fixes plugins to work with pro repeaters

packages/icons/src/genesisIcons.ts, packages/icons/src/index.ts
will allow for including the default gensis icon set without needing to map it yourself if you're a Tailwind user. 
```js
// formkit.config.js
import { generateClasses } from "@formkit/themes"
import { genesis } from "@formkit/themes/tailwindcss"
import { genesisIcons } from "@formkit/icons"
const config = {
config: {
classes: generateClasses(genesis),
},
icons: {
...genesisIcons
},
}
export default config
```
=> adds named export of genesisIcons to assist Tailwind users

packages/themes/src/index.ts
So, the icons were getting into the registry as expected, but the current plugin was checking for existence of something like `select` before removing the `default:` prefix, and `'default:select' !=== 'select'` so the defaults would not be found. This fixes that by changing the order.
=> Moves `iconWasAlreadyLoaded` check to after `defualt:` prefix splitting

packages/themes/package.json
fixes #560 — @justin-schroeder can you let me know if more than this needs to be done? For the time being I'm going to update the documentation to include `dist` in the import path since it won't break anything when beta.15 is out an the non-`dist` path starts working as well.
=> adds `./tailwind/genisis` export path to @formkit/themes package.json

scripts/build.mjs
The `vue` recommendation now is to augment `vue` directly: https://vuejs.org/api/utility-types.html#componentcustomproperties.
It's also possible it might be a volar issue that if you have augmentations of both vue + @vue/compiler-core we also lose typing on GlobalComponents. (So this was causing Nuxt components to be untyped.)
=> fix: augment `vue` without `export`

packages/nuxt/src/module.ts
This PR adds FormKit's documentation to a new custom tab on the Nuxt DevTools, following [official recommandations](https://devtools.nuxtjs.org/module/guide#contributing-to-view).
Note that, for now, you need to use the [DevTools' edge channel](https://github.com/nuxt/devtools#edge-release-channel), as stated in [this recent tweet from Sébastien Chopin](https://twitter.com/Atinux/status/1633376222922039296?s=20).
=> Adds FormKit integration to the Nuxt DevTools

.prettierrc, examples/package.json, examples/src/vue/examples/PerformanceTest.vue, examples/src/vue/examples/Playground.vue, package.json, packages/core/__tests__/node.spec.ts, packages/core/src/node.ts, packages/core/src/schema.ts, packages/inputs/src/inputs/button.ts, packages/inputs/src/inputs/checkbox.ts, packages/inputs/src/inputs/file.ts, packages/inputs/src/inputs/form.ts, packages/inputs/src/inputs/radio.ts, packages/inputs/src/inputs/select.ts, packages/inputs/src/inputs/text.ts, packages/inputs/src/inputs/textarea.ts, packages/observer/__tests__/observer.spec.ts, packages/observer/src/index.ts, packages/validation/src/validation.ts, packages/vue/__tests__/FormKit.spec.ts, packages/vue/src/FormKit.ts, packages/vue/src/FormKitSchema.ts, packages/vue/src/composables/useInput.ts, packages/vue/src/index.ts, pnpm-lock.yaml
This pull requests contains a number of performance enhancements which results in ~3x reduction in "time to mount" compared to previous versions of FormKit. There is still more optimization that can be done, particularly in regards to restructuring code to avoid garbage collection — but most of the super low hanging fruit has been addressed.
- The `input` event will not `disturb` or `commit` changes if the node is an `input` and the value is unchanged.
- `group` and `list` nodes will no longer hydrate children on commit unless there is a change in the child’s value.
- Inputs and schemas can now explicitly define a `schemaMemoKey` to avoid expensive `JSON.stringify()` as a `memoKey` in the schema parser.
- The component level `@input` event will no longer fire until after the node is …
=> Performance improvements

.github/workflows/tests.yml, e2e/memoryNuxt.spec.ts, e2e/memorySSR.spec.ts, e2e/servers/formKitMemoryServer.mjs, package.json, packages/core/src/node.ts, packages/nuxt/package.json, packages/nuxt/playground/.nuxt/tsconfig.json, packages/nuxt/playground/app.vue, packages/nuxt/src/runtime/plugin.mjs, packages/vue/src/FormKit.ts, packages/vue/src/FormKitSchema.ts, packages/vue/src/bindings.ts, packages/vue/src/composables/onSSRComplete.ts, packages/vue/src/index.ts, playwright.config.ts
This PR adds a new global "hook" to `@formkit/vue`: `onSSRComplete`
Since FormKit makes heavy use of memoization and requires a manual cleanup event. This is typically handled on the front end inside `onUnmounted`, but since Vue does not currently have any hooks that fire after SSR we needed to create our own (see: https://github.com/vuejs/core/issues/8066).
This allows any first or third party to manually indicate that SSR has completed and it is safe to perform cleanup operations. This PR implements the new hook in our first-party Nuxt module and adds backing tests.
=> SSR Memory Fixes

packages/themes/src/css/genesis/animations.css, packages/themes/src/css/genesis/inputs/button-and-submit.css, packages/themes/src/css/genesis/inputs/file.css, packages/themes/src/css/genesis/old.css
The css keyframe named `rotate` and `glow` is high probability to conflict with other codebase. 
I think it's better to add prefix before the name
=> fix: prevent css keyframe naming conflict by adding fk prefix

packages/addons/src/plugins/localStoragePlugin.ts
localStorage isn't available on the server in a SSR Nuxt app, but we still want the client to come in and restore the form state. 
This change makes the server skip loading the plugin (and not crash on the server due to lack of localStorage access), allowing the client side to handle this properly.
=> Make localStoragePlugin behave correctly in an SSR context

packages/vue/src/bindings.ts
Fixes #735 by adding a check to see if node is defined at the moment that blur is called, because sometimes the node is destroyed before the blur event is called by the browser in nuxt.
=> Fixes #735: adds node defined check before blur event

examples/src/vue/examples/LocalStoragePlugin.vue, packages/addons/src/plugins/localStoragePlugin.ts
Updated docs with example: https://formkit-com-git-feature-localstorage-plugin-updates-formkit.vercel.app/plugins/local-storage#restoring-values-on-failed-submit
You may need to hard reload to clear cache and get the latest `dev` tag build.
cc: @JoaoPedroAS51
=> adds new node.restoreCache() extension for localStorage plugin

packages/addons/src/plugins/autoAnimatePlugin.ts
The `animationTargets` parameter could be set to any object with properties different to the default one, hence worth checking first whether the properties exist to avoid errors.
=> fix(autoAnimatePlugin): do not assume the existence of default `animationTargets` object

packages/inputs/src/features/icon.ts
This update allows you to provide a literal SVG as the value for `defaultIcon`. Planning to use this for the barcode input package so that we can ship a default barcode SVG while still allowing it to be customized via our existing icon functionality.
=> allows outputting literal SVG code as defaultIcon value

packages/core/src/node.ts, packages/vue/__tests__/FormKit.spec.ts
This PR adds a shortcut for boilerplate `rootClasses: () => ({})`, which could become `rootClasses: false`.
=> feat: allow setting `rootClasses` to false

packages/i18n/src/locales/nl.ts
The current dutch translation sound a bit weird. This PR fixes that.
=> Change three NL locale messages for the `between` validation rule

packages/nuxt/package.json, packages/nuxt/playground/.nuxt/tsconfig.json, packages/nuxt/playground/formkit.config.ts, packages/nuxt/playground/nuxt.config.ts, packages/nuxt/src/module.ts, packages/vue/src/FormKitProvider.ts, pnpm-lock.yaml
In this PR:
An alternative strategy for the `@formkit/nuxt` module. Specifically the module no longer globally installs a plugin, but instead performs direct-injection of a `<FormKitLazyProvider>` at build time. Additionally this alternative strategy uses auto-imports for FormKit components and several functions:
- `<FormKit>`
- `<FormKitProvider>`
`<FormKitMessages>`
`<FormKitSummary>`
`getNode()`
`createInput()`
`setErrors`,
`clearErrors`,
`submitForm`,
`reset`,
`FormKitNode`
=> feat: adds autoImport opt to nuxt module

packages/core/src/node.ts
This PR adds autocompletion for the set of predefined traversal tokens of the `node.at` function, allowing to pass arbitrary string too.
=> chore: autocomplete predefined `node.at` traversal tokens

packages/inputs/src/props.ts
The `decorator` and `decoratorIcon` slots were causing Typescript errors when the checkbox inputs did not have the `options` prop
=> Added decorator types for checkbox slots

packages/nuxt/src/module.ts, packages/nuxt/src/runtime/formkitSSRPlugin.mjs
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
=> fix: import nuxt composables from #imports

packages/i18n/src/locales/en.ts, packages/rules/__tests__/lowercase.spec.ts, packages/rules/src/lowercase.ts
Adds modifiers to the lowercase validation rule:
* allow_non_alpha (allows numbers & the regex from the existing symbols)
* allow_numeric (allows numbers)
* allow_numeric_dashes (allows numbers and dashes)
Also update the messaging in the en locale for lowercase. Running tests locally passed.
=> feat(rules) add modifiers for the lowercase rule

packages/cli/src/createApp.ts
it fixes #1066 by using the interpolation for files instead of `$APP_NAME` that is unix specific.
it also adds a proccess.exit() for safe cancel after it finishes creation.
=> fix: fix windows create-app name for nuxt projects

packages/addons/src/plugins/autoHeightTextarea.ts
Removes the hidden textarea element from the accessibility tree. 
The element violates the following a11y rule from the axe-core tool without removing it from the a11y tree:
["Ensures every form element has a label"](https://dequeuniversity.com/rules/axe/4.8/label?application=axeAPI).
=> Remove hidden textarea element from a11y tree

examples/src/vue/examples/MultiStep.vue, packages/addons/src/plugins/multiStep/schema.ts, packages/addons/src/plugins/multiStep/sections/index.ts, packages/addons/src/plugins/multiStep/sections/wrapper.ts
Fixes #1110
Using `$extend` here was unnecessary and for some reason prevented `sections-schema` prop overrides from being applied to children.
=> fix: fixes issue where multistep tabs and tab schema was not overridable

packages/nuxt/playground/nuxt.config.ts
oops - sorry!
reverts regression from https://github.com/formkit/formkit/pull/1185
=> chore: use relative path for nuxt module playground

packages/nuxt/src/module.ts
Hi - maintainer of the `@nuxtjs/tailwindcss` module here 👋 
I love FormKit and really glad for <https://themes.formkit.com> - let's provide developers convenience of adding their theme file into their Tailwind config automatically?
=> feat(nuxt): add integration with `@nuxtjs/tailwindcss`

packages/addons/src/plugins/multiStep/multiStepPlugin.ts
fixes #1223 because types for BeforeStepChangeData was nextStep instead of targetStep
=> fix: fixes types for BeforeStepChangeData

packages/nuxt/src/module.ts
This seems to be no longer needed; if it recurs in future maybe we can use `resolutions` within the repo here to pin a vite version.
=> fix(nuxt): remove an any

packages/inputs/__tests__/compose.spec.ts, packages/inputs/src/compose.ts
`findSection` uses `eachSection` under the hood. Since https://github.com/formkit/formkit/commit/80628ad3676ae6a8616a6411940698a512087d2b, the loop iterates through conditional sections but the result is never returned: 
```ts
//...
if (schema.then && typeof schema.then !== 'string') {
eachSection(schema.then, callback, stopOnCallbackReturn, schema) // never returned
}
if (schema.else && typeof schema.else !== 'string') {
eachSection(schema.else, callback, stopOnCallbackReturn, schema) // never returned
}
//...
```
Therefore, `stopOnCallbackReturn` becomes useless and `findSection` always returns `[false, false]` when the `eachSection` loop follows one of these paths.
This PR returns the callback result only if `stopOnCallbackReturn` is `true`, which is the case in `findSection`. I also …
=> fix: findSection always returning `[false, false]` when the target is inside a conditional section

scripts/build.mjs, scripts/bundle.mjs
fixes separator for windows, using posix sep.
fixes non node module filter by adding windows `D:` relative path.
=> build: fixes windows build script

packages/themes/__tests__/generateClasses.spec.ts, packages/themes/src/index.ts
Currently it is only allowed to pass a `Record<string, Record<string, string>>` to `generateClasses`.
I often tell myself it would be nice to be able to pass the classes in an array instead of a string, since it allows a better code structure when you have a lot of classes.
Of course, it's still possible to convert the arrays to strings before using `generateClasses`, but that's an additional step that I though could be handled directly by FormKit.
I also fixed some minor type errors and added a test for `generateClasses`.
Have a nice day!
=> feat(themes): allow arrays in `generateClasses` function

.github/workflows/tests.yml, package.json, pnpm-lock.yaml, scripts/build.mjs, scripts/bundle.mjs
Looking into [this failure](https://github.com/formkit/formkit/actions/runs/8491876473/job/23264288414) I improved some type safety for build/bundle scripts, and enabled stubbing the build in CI.
My hypothesis is that it is related to the inability of the dts plugin to resolve types for imports that are not yet stubbed/built ...
=> build: improve type safety and stub before building

packages/themes/package.json, pnpm-lock.yaml
Currently, @formkit/themes has a pinned optional dependency of `unocss` set to a version from [2 years ago](https://github.com/unocss/unocss/releases/tag/v0.31.0), which presents challenges with conflicting dependencies when installing other packages that depend on it.
This pull request updates the optional dependency to the current latest version of `unocss` for review/checks primarily.
=> Update optional 'unocss' dependency to '^0.58.6' in @formkit/themes

packages/inputs/src/props.ts
**Changes list**
- Changed the prop type for `datetime-local` input from camelCase to kebab-case as per the [example usages](https://github.com/formkit/formkit/blob/6b4542a3e013bfff810e126eb20eb2fbce6f25af/examples/src/vue/TextClassifications.vue#L16)
**Additional context**
I've seen [this](https://github.com/formkit/formkit/issues/1129) related issue but we've been still having this problem in the latest version of FormKit (1.6.5). 
Before:
After:
=> Fix casing for the `type` prop of `datetime-local` input

packages/rules/__tests__/date_after_or_equal.spec.ts, packages/rules/__tests__/date_before_or_equal.spec.ts, packages/rules/src/date_after_or_equal.ts, packages/rules/src/date_before_or_equal.ts
Hey there! 👋🏻
This PR introduces two new date validation rules.
Currently, we can’t check if a date is either before or after a specific date and include the option for it to be equal. These new rules address this need, which is a common requirement in many forms.
By adding these rules, we can ensure more accurate validation errors when a date falls outside the allowed range.
=> feat(rules): add "or_equal" date alternative

packages/rules/__tests__/date_after_node.spec.ts, packages/rules/src/date_after_node.ts
Hi, everyone
This PR introduce a new validation to be used with date fields.
The proposal is be able to use `validation="date_after_node:someOtherNode"` in the rules, I faced a problem with it recently and this inspired me to bring a solution that could be used by everyone
=> feat(rules): implements "date_after_node" rule

packages/inputs/src/sections/noFiles.ts
I noticed that if initial value for file type is null or undefined, placeholder is hidden.
Expected:
Received:
=> fix: keep placeholder for null or undefined as well
